version: '3.3'
services:

  teamcity-server:
    container_name: teamcity-server 
    image: jetbrains/teamcity-server:2018.2.2
    ports:
      - "8111:8111"
    volumes:
      - "./teamcity/srv/data:/data/teamcity_server/datadir"
      - "./teamcity/srv/logs:/opt/teamcity/logs"
      - ".:/data/src/repo"

  teamcity-agent-1:
    container_name: teamcity-agent-1
    image: jetbrains/teamcity-agent:2018.2.2
    volumes:
      - "./teamcity/agt-1/conf:/data/teamcity_agent/conf"
      - ".:/data/src/repo"
    environment:
      - SERVER_URL=http://teamcity-server:8111

  teamcity-agent-2:
    container_name: teamcity-agent-2
    image: jetbrains/teamcity-agent:2018.2.2
    volumes:
      - "./teamcity/agt-2/conf:/data/teamcity_agent/conf"
      - ".:/data/src/repo"
    environment:
      - SERVER_URL=http://teamcity-server:8111

  teamcity-agent-3:
    container_name: teamcity-agent-3
    image: jetbrains/teamcity-agent:2018.2.2
    volumes:
      - "./teamcity/agt-3/conf:/data/teamcity_agent/conf"
      - ".:/data/src/repo"
    environment:
      - SERVER_URL=http://teamcity-server:8111
